# Generated by Django 3.1.1 on 2020-09-22 16:04

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres del Autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos del Autor')),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='Imagen del Autor')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('twiter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twiter')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Cración')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('estado', models.BooleanField(default=True, verbose_name='Activada/Desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo del Post')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('descripcion', models.CharField(max_length=110, verbose_name='Descripcion')),
                ('body', ckeditor.fields.RichTextField(max_length=1023, verbose_name='Contenido del Post')),
                ('imagen', models.URLField(blank=True, max_length=255, null=True, verbose_name='Imagen del Post')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Cración')),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No Publicado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Actualización')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posteos',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
