# Generated by Django 3.1.1 on 2020-09-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200909_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['first_name'], 'verbose_name': 'Author', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['create_at'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posteos'},
        ),
    ]
