# Generated by Django 3.1.1 on 2020-09-22 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200922_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='contenido',
        ),
    ]
