# Generated by Django 3.1.1 on 2020-09-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200917_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['nombres'], 'verbose_name': 'Author', 'verbose_name_plural': 'Autores'},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='author',
            name='facebook',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='author',
            name='twiter',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Twiter'),
        ),
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Imagen del Autor'),
        ),
    ]
