# Generated by Django 3.1.1 on 2020-09-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200918_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Imagen del Post'),
        ),
    ]
