# Generated by Django 3.1.1 on 2020-09-18 20:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200918_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres del Autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos del Autor')),
                ('image', models.URLField(blank=True, max_length=255, null=True, verbose_name='Imagen del Autor')),
                ('facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Facebook')),
                ('twiter', models.URLField(blank=True, max_length=255, null=True, verbose_name='Twiter')),
                ('instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Instagram')),
                ('fecha_creacion', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Cración')),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombres'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posteos'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='update_at',
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Cración'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=ckeditor.fields.RichTextField(max_length=1023, verbose_name='Contenido del Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Titulo del Post'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.autor'),
        ),
    ]
