# Generated by Django 3.1.1 on 2020-09-22 16:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='identificador')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono_organizacion', models.CharField(blank=True, help_text='su numero de contacto', max_length=20, verbose_name='Teléfono')),
                ('observacion', models.TextField(verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('ci_nro', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Cedula de identidad')),
                ('telefono_persona', models.CharField(blank=True, help_text='su numero de contacto', max_length=20, verbose_name='Teléfono')),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('observacion', models.TextField(verbose_name='Observacion')),
                ('organizacion', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='legion.organizacion')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['ci_nro'],
            },
        ),
    ]
