# Generated by Django 3.1.1 on 2020-09-09 18:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('contacto', models.CharField(max_length=13)),
                ('observacion', models.TextField()),
            ],
            options={
                'verbose_name': 'Organizacion',
                'verbose_name_plural': 'Organizaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('ci_nro', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='su numero de contacto', max_length=31)),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('fecha_nacimiento', models.DateField()),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('direccion', models.CharField(max_length=100)),
                ('observacion', models.TextField()),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legion.organizacion')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['ci_nro'],
            },
        ),
    ]
