# Generated by Django 3.1.1 on 2020-09-09 18:26

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('legion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='telefono',
            new_name='telefono_persona',
        ),
        migrations.RemoveField(
            model_name='organizacion',
            name='contacto',
        ),
        migrations.AddField(
            model_name='organizacion',
            name='telefono_organizacion',
            field=phone_field.models.PhoneField(blank=True, help_text='su numero de contacto', max_length=31),
        ),
    ]
