# Generated by Django 3.1.1 on 2020-09-22 16:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo de la lección')),
                ('body', ckeditor.fields.RichTextField()),
                ('image', models.CharField(max_length=150, null=True, verbose_name='Link a la Imagen')),
                ('video_leccion', models.CharField(max_length=150, verbose_name='link a video')),
                ('create_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de creación')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Leccion',
                'verbose_name_plural': 'Lecciones',
                'ordering': ['create_at'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo del curso')),
                ('comentario', models.CharField(max_length=200, verbose_name='Comentario')),
                ('video_invitacion', models.CharField(max_length=150, verbose_name='link al video de invitación')),
                ('create_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de creación')),
                ('update_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de actualización')),
                ('lecciones', models.ManyToManyField(to='recursos.Leccion')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['create_at'],
            },
        ),
    ]
